language: python
python:
- "3.6"
branches:
  only:
    - master
before_script:
- pip install conformity
- pip install pytest
- pip install requests
script: pytest && python build_database.py
after_script: now --token=$NOW_TOKEN && now alias --token=$NOW_TOKEN
